version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: master
  reviewers:
    - jlmartyres
    - nikhilPank

- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: master
  reviewers:
    - jlmartyres
    - nikhilPank

- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: master
  reviewers:
    - jlmartyres
    - nikhilPank

- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: master
  reviewers:
    - jlmartyres
    - nikhilPank

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  target-branch: master
  reviewers:
    - jlmartyres
    - nikhilPank
